### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hemangsk** [coala/landing#15]
Hello fellow coalaians!
After initial discussions on how our technology stack should be like and how the website should function, this can be taken a roadmap, and also a progress tracker. This is a fairly rough draft so do pour in your awesome ideas  to make the roadmap more and more efficient 😄  🎉 :-

- [x]   1 : Creating a Flask based REST API structure  [#16](https://github.com/coala/landing/issues/16)

- [x]   2 : Integrating the coala bear search functionality available at gitlab repo [here](https://gitlab.com/coala/new-website), into our Rest API 🚀  🚀  #16 

- [x]   3 : Converting the current HTML page to more modular AngularJS project 💥 . #19 

- [x]   4 : Using Angular, we can create tabs, like in current layout, but more modular and powerful, so when we click the 'LANGUAGES' tab, our Angular will hit our RestAPI and bring all the bears 🐼 . #20

- [ ]   5 : Integration of Try Online, when user clicks on try online, they will be given a live terminal with coala installed so that they can do stuff and get up and running with coala 🐨  🐨 . 

- [ ]   6 : And this should go in parallel with all the above tasks, on the separate branch, we can work on all the major integrations, bug fixing and design nitty gritties on the 'HOME' and 'GET INVOLVED' Tabs, This will include 📖 ,

- [ ]  6a :  Adding coala snippets for multiple languages the the 'getting started section' in the 'HOME' tab 🏛 .

- [ ] 6b : Adding the ascii cinema 🎥 

- [x]  6c: Adding more info about developers in 'GET INVOLVED' 💻  🖥 

- [ ]  6d : Embedding our Gitter chatroom in 'GET INVOLVED' tab. ⌨️  🎹

**Comment by hemangsk** [comment]
cc @sils

**Comment by hemangsk** [comment]
cc @adtac

**Comment by sils** [comment]
@hemangsk so, do we want to use AngularJS or use Elm? We're trying out elm in lots of other places and consistent architecture makes stuff simpler. Also we already spoke about using django since it generates full REST APIs mroe easily.

**Comment by hemangsk** [comment]
@sils IMO if we use Angular for tabs it'll be really great because we'll not have to rely on any third party library apart from Angular, and it has a straight forward approach too. I tried  elm after we discussed on gitter this weekend, to figure out how to create tabs, I think if we go with elm, we will want to use http://debois.github.io/elm-mdl/ or other third party library to provide the required tab interface, but in case of Angular, it will be a hardly 10 minute job to set up Home, GetInvolved, Languages and Try Online in their separate tabs. 
I'd go with any framework, 
But there's a Django v Flask here, - Search bear functionality is written in Flask, but then we also have 'Django REST Framework' which is awesome too. Using Django would mean to rewrite the Flask code.
Thoughts?

**Comment by hemangsk** [comment]
If we go with 

 _Elm + Flask_ 

that'd be great I think, what do you say?

**Comment by hemangsk** [comment]
Started with #1: Creating a Flask based REST API structure

**Comment by arush0311** [comment]
What about react + mui for frontend. The dom manipulation by react is extremely fast

**Comment by ashwini0529** [comment]
@hemangsk take me in loop as well. I'd love to contribute.😁
