### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hemangsk** [coala/landing#46]
Roadmap v2.0 After feasibility discussions, we've decided to throw away flask so that we can improve our database connectivity. So, this one is on how our technology stack should be like and how the website should function, this can be taken as a roadmap, and also a progress tracker. Do pour in your awesome ideas  to make the roadmap more and more efficient 😄  🎉 :-

- [ ]   1 : Creating a Django based REST API structure 

- [ ]   2 : Porting the coala bear search functionality from current flask setup to DRF.

- [x]   3 : Converting the current HTML page to more modular AngularJS project 💥 . #19 

- [x]   4 : Using Angular, we can create tabs, like in current layout, but more modular and powerful, so when we click the 'LANGUAGES' tab, our Angular will hit our RestAPI and bring all the bears 🐼 . #20

- [ ]   5 : Integration of Try Online, when user clicks on try online, they will be given a live terminal with coala installed so that they can do stuff and get up and running with coala 🐨  🐨 . 

 6 : And this should go in parallel with all the above tasks, on the separate branch, we can work on all the major integrations, bug fixing and design nitty gritties on the 'HOME' and 'GET INVOLVED' Tabs, This will include 📖 ,

- [ ]  6a :  Adding coala snippets for multiple languages the the 'getting started section' in the 'HOME' tab 🏛 .

- [ ]  6b : Adding the ascii cinema 🎥 

- [ ]  6c: Adding more info about developers in 'GET INVOLVED' 💻  🖥 

- [ ]  6d : Embedding our Gitter chatroom in 'GET INVOLVED' tab. ⌨️  🎹 

- [ ]  6e:  Bear Analytics
